platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: HelloWorldDotNetCore

run:
  path: sh
  args: ["HelloWorldDotNetCore/ci/tasks/build.sh"]
